

#ifndef CONSTANT_H_
#define CONSTANT_H_



enum {SMB_POV = 0, SMB_SKV = 1, SMB_POV_CALIBR = 2, SMB_USR = 3};
enum {DIM_MM = 0, DIM_MKM = 1};
enum {BAT_NULL = 0, BAT_LOW = 1, BAT_MED = 2, BAT_FULL = 3};
enum {PHASE_USE = 0, PHASE_CALIBR = 1};
enum {SOUND_OFF = 0, SOUND_ON = 1};
enum {USR_MAIN = 0, USR_MEAS_NUM_SET = 1};
enum {HI_SMB_N = 0, HI_SMB_E = 1};

enum {DIM_PICT_US1 = 0, DIM_PICT_US2 = 1, DIM_PICT_MS1 = 2, DIM_PICT_MS2 = 3};
enum {DOT_PICT_INVIS = 0, DOT_PICT_VIS = 1};
enum {SMB_PICT_SKV1 = 0, SMB_PICT_SKV2 = 1, SMB_PICT_POV1 = 2, SMB_PICT_POV2 = 3, SMB_PICT_USR1 = 4, SMB_PICT_USR2 = 5};
enum {BAT_PICT_1F = 0, BAT_PICT_2F = 1, BAT_PICT_2M = 2, BAT_PICT_1L = 3, BAT_PICT_2L = 4, BAT_PICT_1N = 5, BAT_PICT_1N_N = 6};
enum {INTRO3_PICT_BET1 = 0, INTRO3_PICT_BET2 = 1, INTRO3_PICT_VER1 = 2, INTRO3_PICT_VER2 = 3};
enum {INTRO1_PICT_H = 0, INTRO1_PICT_S = 1};

enum {KEY_NO = 15, KEY_AMP_A = 7, KEY_AMP_B = 11, KEY_AMP_C = 13, KEY_AMP_D = 14};
enum {PRESS_NO = 0, PRESS_DOWN = 1, PRESS_QUICK = 2, PRESS_LONG = 3};

enum {FLAG_USR_START = 0, FLAG_KEY_CHANGE = 1, FLAG_FRAME_SHOW = 0, FLAG_BAT_MEAS = 1, FLAG_MEAS = 2, FLAG_PUSH = 3, FLAG_MEAS_NOW = 4,
	FLAG_CH_NUM = 5, FLAG_CH_DIM = 6, FLAG_CH_MODE = 7, FLAG_CH_BAT = 8, FLAG_CH_HI_STR = 9, FLAG_CH_LAMP = 10};
enum {STATE_USR_MEAS_NUM = 0, STATE_MODE = 0, STATE_DIMENSION = 1, STATE_BAT_CHARGE = 2, STATE_LIGHTING = 3, STATE_PHASE = 4,
	STATE_SOUND = 5, STATE_USR = 6, STATE_USR_E = 7, STATE_USR_N = 8, STATE_NUM_BUFFER = 9};

#endif /* CONSTANT_H_ */
